[project]
name = "text-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.8.1",
    "pydantic>=2.10.6",
]


[tool.black]
line-length = 400
